#! /bin/bash
set -e

LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${APPDIR}/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH


QT_PLUGIN_PATH=${LD_LIBRARY_PATH}/qt5/plugins
export QT_PLUGIN_PATH=${QT_PLUGIN_PATH}

cd ${HOME}


${APPDIR}/application/owncloud $@
